---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  second-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Force argocd to delete Kubernetes app 
spec:
  project: default
  source:
    repoURL: https://github.com/rizqiadnan/learn-argo.git
    targetRevision: HEAD
    path: environments/staging/second-app
  destination:
    server: https://kubernetes.default.svc
    # server: https://192.168.49.2:8443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true